### ISSUE TITLE
Requests return status OK but no answer is provided (version 4 24).

### ISSUE THREAD

**Issue by gustavozantut** [rpehkone/Chat-With-RTX-python-api#3]
I am trying to reach ChatRTX via python on top of Docker, i can get status 200 from bot POST and GET requests, but GET returns empty:

![image](https://github.com/rpehkone/Chat-With-RTX-python-api/assets/60036627/a703fbbb-71fa-4174-90b7-7d2e3bdebbdb)

So i tried doing request manually via POSTCode.

POST:

![image](https://github.com/rpehkone/Chat-With-RTX-python-api/assets/60036627/93e34de5-27cd-4bf4-818d-fb28b72e3c2e)

GET:

![image](https://github.com/rpehkone/Chat-With-RTX-python-api/assets/60036627/90f7b92e-569a-4a7c-bd2d-e722b5bb0d5d)

no message returns on GET.
[get_result.txt](https://github.com/rpehkone/Chat-With-RTX-python-api/files/15223907/get_result.txt)

Am i doing something wrong?

Edit:

the code:
[code.txt](https://github.com/rpehkone/Chat-With-RTX-python-api/files/15223974/code.txt)

**Comment by vossr** [comment]
maybe https to url http://host.docker.internal ?

**Comment by gustavozantut** [comment]
> maybe https to url http://host.docker.internal ?

Even on postcode(outside docker) it returns empty(look at post and get requests on prints) , but te request is received and processed with status ok, but get returns empty, in or outside docker.

**Comment by vossr** [comment]
maybe you have some different version,  
in browser second to last post request has the fn_index  
join_queue(session_hash, 100, port, chatdata)

![image](https://github.com/rpehkone/Chat-With-RTX-python-api/assets/57046453/976df4ee-468a-45c1-b4e3-4adb1f5d73d8)

**Comment by gustavozantut** [comment]
mine looks exatcly the same...
![image](https://github.com/rpehkone/Chat-With-RTX-python-api/assets/60036627/af1be8c3-5644-4dd0-b73d-e008b40a6005)

**Comment by GnatGoSplat** [comment]
I'm having the same problem.  Response [200] for Listen and Join.  Nothing returned.  0 tokens.  I'm not using Docker.  Just default 4_24 install trying to reach it with python on local.

**Comment by Kepilif** [comment]
The issue persists as previously mentioned (@GnatGoSplat); no results were obtained.

**Comment by gustavozantut** [comment]
i was taking a look at the code and it seems that the chat is not doing simple get and post requests on 4.24, it's using generators and yeld

**Comment by vossr** [comment]
Automatically find the stream completion function https://github.com/rpehkone/Chat-With-RTX-python-api/blob/master/rtx_api_4_24.py#L90
Should work, wasn't able to reproduce the issue.

**Comment by gustavozantut** [comment]
That's because ur not running 4.24 version, in your picture there's no option for photo upload(but version 4.24 allows photo upload)

**Comment by gustavozantut** [comment]
working, lov u

**Comment by GnatGoSplat** [comment]
Thanks, the fix is working for me.  It's causing a bunch of errors in the ChatRTX Powershell window, but they seem inconsequential.
