### ISSUE TITLE
chatrtx v0.4.0

### ISSUE THREAD

**Issue by Bilalline** [rpehkone/Chat-With-RTX-python-api#5]
How can I send or receive requests on the new version of chatrtx 4.0? This new version does not have a web interface and the program opens in a window. the rtx_api_4_24.py file reports that it could not find the port.

**Comment by vossr** [comment]
ok this starts a custom process https://github.com/rpehkone/Chat-With-RTX-python-api/blob/master/rtx_server_july_2024.py

**Comment by Bilalline** [comment]
отлично, это работает!
пришлось немного поправить код для работы с русским языком.

```
from http.client import HTTPConnection

def send_message(message):
    connection = HTTPConnection('ip', port)
    headers = {'Content-type': 'text/plain; charset=utf-8'}
    encoded_message = message.encode('utf-8')
    connection.request('POST', '/', encoded_message, headers)
    response = connection.getresponse()

    if response.status == 200:
        return response.read().decode('utf-8')
    else:
        raise Exception("Error: Server responded with status {}".format(response.status))
```
